version: '2'

services:
    elasticsearch:
        image: elasticsearch:2.4
        container_name: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - $PWD/esdata:/usr/share/elasticsearch/data

    kibana:
        image: kibana:4.6
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            - "ELASTICSEARCH_URL=http://elasticsearch:9200"